const N = 5
const W = 40

const FLOOR_HEIGHT = 100
const FLOOR_WIDTH = 500

const LIFT_VELOCITY = 0.02
const WORKER_VELOCITY = 1
const LIFT_CLOSE_DOOR_COUNTDOWN = 30
const WORKER_SLACKING_COUNTDOWN = 30
const LIFT_AREA = [50, 120]
const LIFT_BORDING_ZONE = 20
